---
- hosts: terrarium
  become: true
  remote_user: sylvain

  vars:
    # Mount points
    # mounts:
    #   - path: /media/big
    #     src: UUID=b365daec-de01-4e3a-9d0c-f91e7748f0ac
    #     fstype: btrfs
    #     opts: defaults

    smartd_devices:
      /dev/sda: {}
      /dev/sdb: {}
      /dev/sdc: {}
    alerting:
      mail_frequency: diminishing
      temperature_report_info: 45
      temperature_report_crit: 55
      script: /usr/local/alert-disk.sh

  roles:
    - smartd